//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eziou.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Items = new HashSet<Item>();
            this.Participants = new HashSet<Participant>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
    }
}
