//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eziou.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Consumers = new HashSet<Participant>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EventId { get; set; }
        public System.Guid ParticipantId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Participant Provider { get; set; }
        public virtual ICollection<Participant> Consumers { get; set; }
    }
}
