//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eziou.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.ProvidedItems = new HashSet<Item>();
            this.ConsumedItems = new HashSet<Item>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid EventId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ICollection<Item> ProvidedItems { get; set; }
        public virtual ICollection<Item> ConsumedItems { get; set; }
    }
}
